### ISSUE TITLE
Changes to facilitate migrating Micronaut CLI to picocli

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#387]
Micronaut ticket: https://github.com/micronaut-projects/micronaut-core/issues/256

Related:
- [x] #288 command aliases
- [x] #389 Support 'lenient' parsing mode  
- [x] #391 Add API to get completion candidates for Option and Positional Parameter values 
- [x] #392 Map command line arguments to picocli spec elements in `ParseResult` 
- [x] #393 Add support for JLine completers
- [x] #259 Support @Inject annotation to inject CommandSpec into command implementation
- [x] #398 Allow @PicocliScript annotation on Groovy script @Field variables 

Not required:
- #242 interactive cli (tokenizer may not be needed as client applications can use the one built into JLine2)
 - #298 Add help for mistyped commands - AbstractProfile implements this with `CosineSimilarity.mostSimilar`; when flags are mistyped, picocli will already generate a user-friendly error message and print usage help for the command, so specific processing like in `CreateAppCommand` is unnecessary.
