### ISSUE TITLE
Remaining todo items for supporting `@Command`-annotated methods

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#455]
Some todos remain from PR #416:

* [x] (WON'T FIX) _Remove the `@Command(addMethodSubcommands)` attribute and add method commands automatically as subcommands if (and only if) the class has a `@Command` annotation._ I changed my mind on this; it is useful to be able to switch this off if needed.
* [x] (WON'T FIX) _Make the `CommandLine#addMethodSubcommands` and `getCommandMethods` methods private to reduce the public API surface._ I removed `addMethodSubcommands` (it wasn't used), but changed my mind on the `getCommandMethods` method and keeping it.
* [x] Don't mix in options/positional params from the containing class `@Command` into the method commands. 
* [x] Command methods should be able to mix in the standard help options. 
* [x] Bugfix: unannotated method parameters should be assigned a positional index matching their parameter index (but skipping `@Option` method parameters)
* [x] New feature: if compiled with the `-parameters` flag on Java 8 or higher, the method parameter name should be obtained with `java.lang.reflect.Parameter#getName` using reflection instead of the generic `arg0`, `arg1`, etc. 
* [ ] Add documentation for `@Command` methods. Ideally add a recommendation on when to use which annotation style. (Location could be after [15.1 Annotated Methods](https://picocli.info/#_annotated_methods) or perhaps a separate page.)
